# Generated by Django 2.2.3 on 2019-07-31 03:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=1, null=True)),
                ('email', models.CharField(max_length=100)),
                ('date_register', models.DateTimeField(default=datetime.datetime(2019, 7, 31, 3, 10, 10, 643507))),
            ],
        ),
    ]
