# Generated by Django 2.2.3 on 2019-07-31 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercrud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date_register',
            field=models.DateField(default=datetime.datetime(2019, 7, 31, 3, 46, 59, 971951)),
        ),
    ]
