# Generated by Django 2.1.2 on 2019-08-01 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercrud', '0002_auto_20190731_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date_register',
            field=models.DateField(default=datetime.datetime(2019, 8, 1, 8, 59, 16, 555536)),
        ),
    ]
