# Generated by Django 2.2.3 on 2019-08-02 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercrud', '0004_auto_20190802_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date_register',
            field=models.DateField(default=datetime.datetime(2019, 8, 2, 5, 33, 18, 961321)),
        ),
    ]
