version: '2'

services:
      noteservices:
        image: noteservices
        container_name: noteservices
        command: "bash -c 'python manage.py migrate --no-input && python manage.py runserver 0.0.0.0:8001'"
        ports:
          - 8001:8001
        depends_on:
          - mongo2
        restart: always
        links:
          - mongo2
      
      mongo2:
        image: mongo
        container_name: mongoplayvox2
        environment:
          - MONGODB_DATABASE=notes
        volumes:
          - ./db:/var/lib/mongo2
        restart: always
