# Generated by Django 2.1.2 on 2019-08-01 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='register',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 1, 14, 47, 48, 113000)),
        ),
    ]
