# Generated by Django 2.2.3 on 2019-08-02 02:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20190801_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='register',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 2, 2, 45, 40, 144481)),
        ),
    ]
